name: Inspeccionar Cache Zenon

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    # 1. Gestiona la caché en los servidores de GitHub usando tu clave
    - name: Configurar Caché de Zenon
      uses: actions/cache@v4
      with:
        path: .github/workflows
        key: ${{ runner.os }}-zenon-knowledge-${{ hashFiles('.github/workflows/*.yml') }}

    # 2. Genera el Artifact descargable en la web para ver tus archivos .yml
    - name: 📦 Guardar copia visual en la web (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: copia-inspeccion-cache
        path: .github/workflows

